// spikes/latency/src/report.ts
import fs from "node:fs";
import path from "node:path";
import { percentile } from "./stats.js";
import { CONFIG, ROOT } from "./config.js";
import type { TimingRecord } from "./pipeline.js";

const OUT_DIR = path.join(ROOT, "out");
const TIMINGS = path.join(OUT_DIR, "timings.jsonl");
const RESULTS = path.join(OUT_DIR, "results.md");

type DerivedKey = keyof NonNullable<TimingRecord["derived"]>;

const METRICS: ReadonlyArray<readonly [string, DerivedKey]> = [
  ["STT round trip", "sttMs"],
  ["LLM time-to-first-token", "ttftMs"],
  ["LLM first sentence boundary", "firstBoundaryMs"],
  ["LLM full generation", "llmMs"],
  ["TTS first chunk", "ttsChunkMs"],
  ["TTS full reply", "ttsFullMs"],
  ["**TTFA chunked**", "ttfaChunkedMs"],
  ["**TTFA unchunked**", "ttfaUnchunkedMs"],
];

const fmt = (v: number) => `${(v / 1000).toFixed(2)}s`;

function metricTable(records: TimingRecord[]): string {
  const rows = METRICS.map(([label, key]) => {
    const vals = records.map((r) => r.derived![key]);
    return `| ${label} | ${fmt(percentile(vals, 50))} | ${fmt(percentile(vals, 90))} |`;
  });
  return ["| metric | p50 | p90 |", "|---|---|---|", ...rows].join("\n");
}

function main() {
  if (!fs.existsSync(TIMINGS)) throw new Error(`${TIMINGS} not found — run \`npm run run\` first`);
  const records = fs
    .readFileSync(TIMINGS, "utf8")
    .trim()
    .split("\n")
    .map((l) => JSON.parse(l) as TimingRecord);
  const ok = records.filter((r) => r.ok);
  const failed = records.filter((r) => !r.ok);
  if (ok.length === 0) throw new Error("no successful runs in timings.jsonl");

  const clipIds = [...new Set(ok.map((r) => r.clipId))];
  const coldStarts = ok.filter((r) => r.coldStart).length;
  const flushChunks = ok.filter((r) => r.chunkFromFlush).length;

  const sections: string[] = [
    "# Latency Spike — Results",
    "",
    "Generated by `npm run report`. Do not edit by hand.",
    "",
    `${records.length} recorded runs: ${ok.length} ok, ${failed.length} failed (excluded from percentiles).`,
    "",
    "## All clips pooled",
    "",
    metricTable(ok),
  ];

  for (const id of clipIds) {
    const subset = ok.filter((r) => r.clipId === id);
    const label = CONFIG.clips.find((c) => c.id === id)?.label ?? "?";
    sections.push("", `## Clip ${id} (${label}, n=${subset.length})`, "", metricTable(subset));
  }

  sections.push(
    "",
    "## Notes",
    "",
    `- Cold-start runs included in the data: ${coldStarts} (flagged \`coldStart\` in timings.jsonl)`,
    `- Runs whose first chunk only appeared at stream end (no mid-stream boundary): ${flushChunks}`,
    failed.length > 0
      ? `- Excluded failures: ${failed.map((r) => `${r.clipId}#${r.iteration} (${r.error})`).join("; ")}`
      : "- Excluded failures: none",
    "",
    "## Config",
    "",
    "```json",
    JSON.stringify(
      {
        sttModel: CONFIG.sttModel,
        llmModel: CONFIG.llmModel,
        ttsModel: CONFIG.ttsModel,
        ttsVoice: CONFIG.ttsVoice,
        maxCompletionTokens: CONFIG.maxCompletionTokens,
        minChunkLength: CONFIG.minChunkLength,
        iterations: CONFIG.iterations,
        interRunDelayMs: CONFIG.interRunDelayMs,
        ttfaTargetMs: CONFIG.ttfaTargetMs,
        clips: CONFIG.clips.map((c) => `${c.id} (${c.label})`),
      },
      null,
      2
    ),
    "```",
    ""
  );

  const tmp = RESULTS + ".tmp";
  fs.writeFileSync(tmp, sections.join("\n"));
  fs.renameSync(tmp, RESULTS);
  console.log(`wrote ${RESULTS} (${ok.length} ok runs, ${failed.length} excluded)`);
}

main();
